# Generated by Django 4.1 on 2022-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
        migrations.AlterField(
            model_name='product',
            name='imgage',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec',
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
