# Generated by Django 4.1 on 2022-08-23 08:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('thumbnail', django.db.models.manager.Manager()),
            ],
        ),
    ]
