# Generated by Django 4.1 on 2022-08-19 12:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_available_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('Procent discount', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=mptt.fields.TreeForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.PROTECT, to='catalog.sales'),
        ),
    ]
