# Generated by Django 4.1 on 2022-08-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_sales_product_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='Procent discount',
        ),
    ]
