# Generated by Django 4.1 on 2022-08-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_sales_procent discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='Procent discount',
        ),
    ]
