# Generated by Django 4.1 on 2022-08-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_sales_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
    ]
