# Generated by Django 4.1 on 2022-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.BooleanField(default=False),
        ),
    ]
