# Generated by Django 4.1 on 2022-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_amount',
            field=models.IntegerField(default=0),
        ),
    ]
