version: '3.8'

services:
  web:
    build: ./
    command: ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev